/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as CreditRouteImport } from './routes/credit'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as PairsRouteImport } from './routes/pairs'
import { Route as PitchRouteImport } from './routes/pitch'
import { Route as PreipoRouteImport } from './routes/preipo'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TruthRouteImport } from './routes/truth'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskAcquireRouteImport } from './routes/desk.acquire'
import { Route as DeskActivityRouteImport } from './routes/desk.activity'
import { Route as DeskAdminRouteImport } from './routes/desk.admin'
import { Route as DeskCreditRouteImport } from './routes/desk.credit'
import { Route as DeskMarketsRouteImport } from './routes/desk.markets'
import { Route as DeskPositionsRouteImport } from './routes/desk.positions'
import { Route as DeskPreipoRouteImport } from './routes/desk.preipo'
import { Route as DeskSettingsRouteImport } from './routes/desk.settings'
import { Route as DeskTesseraRouteImport } from './routes/desk.tessera'
import { Route as LabShadersRouteImport } from './routes/lab.shaders'
import { Route as LabUiRouteImport } from './routes/lab.ui'
import { Route as DeskPositionsSymbolRouteImport } from './routes/desk.positions_.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRoute = CreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const PairsRoute = PairsRouteImport.update({
  id: '/pairs',
  path: '/pairs',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchRoute = PitchRouteImport.update({
  id: '/pitch',
  path: '/pitch',
  getParentRoute: () => rootRouteImport,
} as any)
const PreipoRoute = PreipoRouteImport.update({
  id: '/preipo',
  path: '/preipo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TruthRoute = TruthRouteImport.update({
  id: '/truth',
  path: '/truth',
  getParentRoute: () => rootRouteImport,
} as any)
const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskAcquireRoute = DeskAcquireRouteImport.update({
  id: '/acquire',
  path: '/acquire',
  getParentRoute: () => DeskRoute,
} as any)
const DeskActivityRoute = DeskActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DeskRoute,
} as any)
const DeskAdminRoute = DeskAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCreditRoute = DeskCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => DeskRoute,
} as any)
const DeskMarketsRoute = DeskMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPositionsRoute = DeskPositionsRouteImport.update({
  id: '/positions',
  path: '/positions',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPreipoRoute = DeskPreipoRouteImport.update({
  id: '/preipo',
  path: '/preipo',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSettingsRoute = DeskSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTesseraRoute = DeskTesseraRouteImport.update({
  id: '/tessera',
  path: '/tessera',
  getParentRoute: () => DeskRoute,
} as any)
const LabShadersRoute = LabShadersRouteImport.update({
  id: '/lab/shaders',
  path: '/lab/shaders',
  getParentRoute: () => rootRouteImport,
} as any)
const LabUiRoute = LabUiRouteImport.update({
  id: '/lab/ui',
  path: '/lab/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskPositionsSymbolRoute = DeskPositionsSymbolRouteImport.update({
  id: '/positions_/$symbol',
  path: '/positions/$symbol',
  getParentRoute: () => DeskRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beta': typeof BetaRoute
  '/credit': typeof CreditRoute
  '/desk': typeof DeskRouteWithChildren
  '/execution': typeof ExecutionRoute
  '/markets': typeof MarketsRoute
  '/network': typeof NetworkRoute
  '/pairs': typeof PairsRoute
  '/pitch': typeof PitchRoute
  '/preipo': typeof PreipoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/truth': typeof TruthRoute
  '/whitepaper': typeof WhitepaperRoute
  '/desk/acquire': typeof DeskAcquireRoute
  '/desk/activity': typeof DeskActivityRoute
  '/desk/admin': typeof DeskAdminRoute
  '/desk/credit': typeof DeskCreditRoute
  '/desk/markets': typeof DeskMarketsRoute
  '/desk/positions': typeof DeskPositionsRoute
  '/desk/preipo': typeof DeskPreipoRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/tessera': typeof DeskTesseraRoute
  '/lab/shaders': typeof LabShadersRoute
  '/lab/ui': typeof LabUiRoute
  '/desk/': typeof DeskIndexRoute
  '/desk/positions/$symbol': typeof DeskPositionsSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beta': typeof BetaRoute
  '/credit': typeof CreditRoute
  '/execution': typeof ExecutionRoute
  '/markets': typeof MarketsRoute
  '/network': typeof NetworkRoute
  '/pairs': typeof PairsRoute
  '/pitch': typeof PitchRoute
  '/preipo': typeof PreipoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/truth': typeof TruthRoute
  '/whitepaper': typeof WhitepaperRoute
  '/desk/acquire': typeof DeskAcquireRoute
  '/desk/activity': typeof DeskActivityRoute
  '/desk/admin': typeof DeskAdminRoute
  '/desk/credit': typeof DeskCreditRoute
  '/desk/markets': typeof DeskMarketsRoute
  '/desk/positions': typeof DeskPositionsRoute
  '/desk/preipo': typeof DeskPreipoRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/tessera': typeof DeskTesseraRoute
  '/lab/shaders': typeof LabShadersRoute
  '/lab/ui': typeof LabUiRoute
  '/desk': typeof DeskIndexRoute
  '/desk/positions/$symbol': typeof DeskPositionsSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/beta': typeof BetaRoute
  '/credit': typeof CreditRoute
  '/desk': typeof DeskRouteWithChildren
  '/execution': typeof ExecutionRoute
  '/markets': typeof MarketsRoute
  '/network': typeof NetworkRoute
  '/pairs': typeof PairsRoute
  '/pitch': typeof PitchRoute
  '/preipo': typeof PreipoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/truth': typeof TruthRoute
  '/whitepaper': typeof WhitepaperRoute
  '/desk/acquire': typeof DeskAcquireRoute
  '/desk/activity': typeof DeskActivityRoute
  '/desk/admin': typeof DeskAdminRoute
  '/desk/credit': typeof DeskCreditRoute
  '/desk/markets': typeof DeskMarketsRoute
  '/desk/positions': typeof DeskPositionsRoute
  '/desk/preipo': typeof DeskPreipoRoute
  '/desk/settings': typeof DeskSettingsRoute
  '/desk/tessera': typeof DeskTesseraRoute
  '/lab/shaders': typeof LabShadersRoute
  '/lab/ui': typeof LabUiRoute
  '/desk/': typeof DeskIndexRoute
  '/desk/positions_/$symbol': typeof DeskPositionsSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/beta'
    | '/credit'
    | '/desk'
    | '/execution'
    | '/markets'
    | '/network'
    | '/pairs'
    | '/pitch'
    | '/preipo'
    | '/privacy'
    | '/terms'
    | '/truth'
    | '/whitepaper'
    | '/desk/acquire'
    | '/desk/activity'
    | '/desk/admin'
    | '/desk/credit'
    | '/desk/markets'
    | '/desk/positions'
    | '/desk/preipo'
    | '/desk/settings'
    | '/desk/tessera'
    | '/lab/shaders'
    | '/lab/ui'
    | '/desk/'
    | '/desk/positions/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/beta'
    | '/credit'
    | '/execution'
    | '/markets'
    | '/network'
    | '/pairs'
    | '/pitch'
    | '/preipo'
    | '/privacy'
    | '/terms'
    | '/truth'
    | '/whitepaper'
    | '/desk/acquire'
    | '/desk/activity'
    | '/desk/admin'
    | '/desk/credit'
    | '/desk/markets'
    | '/desk/positions'
    | '/desk/preipo'
    | '/desk/settings'
    | '/desk/tessera'
    | '/lab/shaders'
    | '/lab/ui'
    | '/desk'
    | '/desk/positions/$symbol'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/beta'
    | '/credit'
    | '/desk'
    | '/execution'
    | '/markets'
    | '/network'
    | '/pairs'
    | '/pitch'
    | '/preipo'
    | '/privacy'
    | '/terms'
    | '/truth'
    | '/whitepaper'
    | '/desk/acquire'
    | '/desk/activity'
    | '/desk/admin'
    | '/desk/credit'
    | '/desk/markets'
    | '/desk/positions'
    | '/desk/preipo'
    | '/desk/settings'
    | '/desk/tessera'
    | '/lab/shaders'
    | '/lab/ui'
    | '/desk/'
    | '/desk/positions_/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BetaRoute: typeof BetaRoute
  CreditRoute: typeof CreditRoute
  DeskRoute: typeof DeskRouteWithChildren
  ExecutionRoute: typeof ExecutionRoute
  MarketsRoute: typeof MarketsRoute
  NetworkRoute: typeof NetworkRoute
  PairsRoute: typeof PairsRoute
  PitchRoute: typeof PitchRoute
  PreipoRoute: typeof PreipoRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TruthRoute: typeof TruthRoute
  WhitepaperRoute: typeof WhitepaperRoute
  LabShadersRoute: typeof LabShadersRoute
  LabUiRoute: typeof LabUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit': {
      id: '/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof CreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairs': {
      id: '/pairs'
      path: '/pairs'
      fullPath: '/pairs'
      preLoaderRoute: typeof PairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch': {
      id: '/pitch'
      path: '/pitch'
      fullPath: '/pitch'
      preLoaderRoute: typeof PitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preipo': {
      id: '/preipo'
      path: '/preipo'
      fullPath: '/preipo'
      preLoaderRoute: typeof PreipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truth': {
      id: '/truth'
      path: '/truth'
      fullPath: '/truth'
      preLoaderRoute: typeof TruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/acquire': {
      id: '/desk/acquire'
      path: '/acquire'
      fullPath: '/desk/acquire'
      preLoaderRoute: typeof DeskAcquireRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/activity': {
      id: '/desk/activity'
      path: '/activity'
      fullPath: '/desk/activity'
      preLoaderRoute: typeof DeskActivityRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/admin': {
      id: '/desk/admin'
      path: '/admin'
      fullPath: '/desk/admin'
      preLoaderRoute: typeof DeskAdminRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/credit': {
      id: '/desk/credit'
      path: '/credit'
      fullPath: '/desk/credit'
      preLoaderRoute: typeof DeskCreditRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/markets': {
      id: '/desk/markets'
      path: '/markets'
      fullPath: '/desk/markets'
      preLoaderRoute: typeof DeskMarketsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/positions': {
      id: '/desk/positions'
      path: '/positions'
      fullPath: '/desk/positions'
      preLoaderRoute: typeof DeskPositionsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/preipo': {
      id: '/desk/preipo'
      path: '/preipo'
      fullPath: '/desk/preipo'
      preLoaderRoute: typeof DeskPreipoRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/settings': {
      id: '/desk/settings'
      path: '/settings'
      fullPath: '/desk/settings'
      preLoaderRoute: typeof DeskSettingsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/tessera': {
      id: '/desk/tessera'
      path: '/tessera'
      fullPath: '/desk/tessera'
      preLoaderRoute: typeof DeskTesseraRouteImport
      parentRoute: typeof DeskRoute
    }
    '/lab/shaders': {
      id: '/lab/shaders'
      path: '/lab/shaders'
      fullPath: '/lab/shaders'
      preLoaderRoute: typeof LabShadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/ui': {
      id: '/lab/ui'
      path: '/lab/ui'
      fullPath: '/lab/ui'
      preLoaderRoute: typeof LabUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/positions_/$symbol': {
      id: '/desk/positions_/$symbol'
      path: '/positions/$symbol'
      fullPath: '/desk/positions/$symbol'
      preLoaderRoute: typeof DeskPositionsSymbolRouteImport
      parentRoute: typeof DeskRoute
    }
  }
}

interface DeskRouteChildren {
  DeskAcquireRoute: typeof DeskAcquireRoute
  DeskActivityRoute: typeof DeskActivityRoute
  DeskAdminRoute: typeof DeskAdminRoute
  DeskCreditRoute: typeof DeskCreditRoute
  DeskMarketsRoute: typeof DeskMarketsRoute
  DeskPositionsRoute: typeof DeskPositionsRoute
  DeskPreipoRoute: typeof DeskPreipoRoute
  DeskSettingsRoute: typeof DeskSettingsRoute
  DeskTesseraRoute: typeof DeskTesseraRoute
  DeskIndexRoute: typeof DeskIndexRoute
  DeskPositionsSymbolRoute: typeof DeskPositionsSymbolRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskAcquireRoute: DeskAcquireRoute,
  DeskActivityRoute: DeskActivityRoute,
  DeskAdminRoute: DeskAdminRoute,
  DeskCreditRoute: DeskCreditRoute,
  DeskMarketsRoute: DeskMarketsRoute,
  DeskPositionsRoute: DeskPositionsRoute,
  DeskPreipoRoute: DeskPreipoRoute,
  DeskSettingsRoute: DeskSettingsRoute,
  DeskTesseraRoute: DeskTesseraRoute,
  DeskIndexRoute: DeskIndexRoute,
  DeskPositionsSymbolRoute: DeskPositionsSymbolRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BetaRoute: BetaRoute,
  CreditRoute: CreditRoute,
  DeskRoute: DeskRouteWithChildren,
  ExecutionRoute: ExecutionRoute,
  MarketsRoute: MarketsRoute,
  NetworkRoute: NetworkRoute,
  PairsRoute: PairsRoute,
  PitchRoute: PitchRoute,
  PreipoRoute: PreipoRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TruthRoute: TruthRoute,
  WhitepaperRoute: WhitepaperRoute,
  LabShadersRoute: LabShadersRoute,
  LabUiRoute: LabUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
